#[derive(Debug, PartialEq)]
pub enum JSONParseError {
    QuoteCharAfterKeyClose,
    QuoteCharAfterValueClose,
    QuoteCharInNonStringData,
    UnexpectedQuoteChar,
    UnexpectedCharInNonStringData,
    UnexpectedEscape,
    UnexpectedComma,
    UnexpectedColon,
    UnexpectedOpenBracket,
    UnexpectedCloseBracket,
    UnexpectedOpenBrace,
    UnexpectedCloseBrace,
    InvalidCharEncountered,
    InvalidCharInNumber,
    InvalidCharInLiteral,
    InvalidNonStringDataFirstChar,
    TokenParseErrorMisc(&'static str),
}
